<template><view class="page">
  <view class="steps"><view class="active"><b>1</b><span>客户与时间</span></view><i></i><view><b>2</b><span>台位与套餐</span></view></view>
  <view class="card"><text class="title">客户信息</text><label><span>客户姓名</span><input v-model="customerName" placeholder="请输入客户姓名"/></label><label><span>手机号码</span><input v-model="phone" type="number" maxlength="11" placeholder="请输入手机号码"/></label><label><span>客户微信</span><input v-model="wechat" placeholder="选填"/></label></view>
  <view class="card"><text class="title">预订信息</text><picker mode="date" :value="date" @change="date=($event as any).detail.value"><label><span>到店日期</span><text>{{date}} ›</text></label></picker><picker mode="time" :value="time" @change="time=($event as any).detail.value"><label><span>预计到店</span><text>{{time}} ›</text></label></picker><label><span>到店人数</span><input v-model.number="guestCount" type="number"/></label><label @click="chooseTable"><span>预订台位</span><text :class="{placeholder:!tableId}">{{tableId||'点击选择'}} ›</text></label></view>
  <view class="card"><text class="title">套餐选择</text><view v-for="p in packages" :key="p.name" :class="['package',{active:selectedPackage===p}]" @click="selectedPackage=p"><view><b>{{p.name}}</b><span>{{p.desc}}</span></view><text>¥{{p.price}}</text></view></view>
  <view class="bottom"><view><span>订单金额</span><b>¥{{selectedPackage?.price||0}}</b></view><button @click="submit">创建预订</button></view>
</view></template>
<script setup lang="ts">
import{ref}from'vue';import{onLoad}from'@dcloudio/uni-app';import{createOrder}from'../../services/orders'
const customerName=ref(''),phone=ref(''),wechat=ref(''),date=ref(new Date(Date.now()+86400000).toISOString().slice(0,10)),time=ref('22:30'),guestCount=ref(6),tableId=ref(''),packages=[{name:'经典畅饮套餐',desc:'威士忌 1 瓶 · 软饮 6 瓶 · 果盘',price:2880},{name:'尊享香槟套餐',desc:'香槟 2 瓶 · 软饮 8 瓶 · 果盘',price:3880},{name:'暂不选择套餐',desc:'到店后由服务员加单',price:0}],selectedPackage=ref(packages[0])
onLoad((q:any)=>{if(q?.table)tableId.value=q.table});const chooseTable=()=>uni.showActionSheet({itemList:['V01 · VIP区','V02 · VIP区','A01 · 卡座区','A02 · 卡座区','B01 · 卡座区'],success:r=>tableId.value=['V01','V02','A01','A02','B01'][r.tapIndex]})
const submit=()=>{if(!customerName.value||!/^1\d{10}$/.test(phone.value)||!tableId.value)return uni.showToast({title:'请完善客户、手机号和台位',icon:'none'});const p=selectedPackage.value;createOrder({tableId:tableId.value,customerName:customerName.value,phone:phone.value,wechat:wechat.value,salesName:'演示员工',date:date.value,arrivalTime:time.value,guestCount:guestCount.value,status:'reserved',items:p.price?[{name:p.name,qty:1,price:p.price}]:[]});uni.showToast({title:'预订创建成功',icon:'success'});setTimeout(()=>uni.redirectTo({url:'/pages/orders/index'}),700)}
</script>
<style scoped>
.page{min-height:100vh;background:#f5f5f5;color:#222;padding:18px 15px 90px}.steps{display:flex;align-items:center;justify-content:center;margin:5px 0 20px}.steps view{display:flex;align-items:center;color:#aaa;font-size:10px}.steps b{width:23px;height:23px;border-radius:50%;background:#ddd;color:#fff;display:flex;align-items:center;justify-content:center;margin-right:6px}.steps .active{color:#07c160}.steps .active b{background:#07c160}.steps i{width:48px;height:1px;background:#ddd;margin:0 10px}.card{background:#fff;border-radius:12px;padding:0 15px;margin-bottom:12px}.title{display:block;font-size:15px;font-weight:700;padding:17px 0 8px}.card label{min-height:53px;border-bottom:1px solid #f0f0f0;display:flex;align-items:center;font-size:12px}.card label:last-child{border:0}.card label span{width:82px;color:#666}.card input{flex:1;text-align:right;font-size:12px}.card label>text{margin-left:auto}.placeholder{color:#aaa}.package{min-height:72px;border:1px solid #eee;border-radius:9px;margin:9px 0;padding:13px;display:flex;align-items:center}.package:last-child{margin-bottom:16px}.package.active{border:1.5px solid #07c160;background:#f1fbf4}.package view{flex:1}.package b,.package span{display:block}.package b{font-size:12px}.package span{font-size:9px;color:#999;margin-top:6px}.package>text{font-size:14px;font-weight:700}.bottom{position:fixed;bottom:0;left:50%;transform:translateX(-50%);width:min(480px,100%);height:72px;background:#fff;border-top:1px solid #eee;padding:10px 15px;display:flex;align-items:center}.bottom view{flex:1}.bottom span,.bottom b{display:block}.bottom span{font-size:9px;color:#999}.bottom b{font-size:19px;color:#e54d42;margin-top:3px}.bottom button{margin:0;width:170px;height:48px;background:#07c160;color:#fff;border-radius:7px;font-size:13px}
</style>
