<template><view class="page">
  <view class="head"><text class="eyebrow">MEMBERSHIP</text><text class="title">会员中心</text></view>
  <view class="member-card"><view class="shine"></view><view class="card-top"><text class="brand">H<span>O</span>LE</text><text class="chip">◇</text></view><text class="tier">BLACK</text><view class="card-bottom"><view><span>MEMBER</span><b>体验会员</b></view><text>NO. 000888</text></view></view>
  <view class="stats"><view><b>{{validCount}}</b><span>有效预订</span></view><view><b>0</b><span>会员积分</span></view><view><b>2</b><span>可用权益</span></view></view>
  <view class="section-head"><text>专属权益</text><span>查看全部 →</span></view>
  <view class="benefits">
    <view><text class="icon">⌁</text><view><b>优先留台</b><span>热门日期享优先预订机会</span></view><text class="arrow">›</text></view>
    <view><text class="icon">✦</text><view><b>生日礼遇</b><span>生日月到店获赠专属礼遇</span></view><text class="arrow">›</text></view>
    <view class="locked"><text class="icon">◇</text><view><b>会员专享价</b><span>升级 SILVER 后解锁</span></view><text class="arrow">锁定</text></view>
  </view>
  <view class="progress"><view class="progress-head"><text>距离 SILVER</text><b>0 / 1,000</b></view><view class="track"><span></span></view><text class="hint">消费积累积分，即可升级解锁更多权益</text></view>
  <view class="nav"><view @click="goHome"><text>○</text><span>首页</span></view><view @click="goBooking"><text>⌁</text><span>订台</span></view><view @click="goOrders"><text>≡</text><span>订单</span></view><view class="active"><text>◇</text><span>我的</span></view></view>
</view></template>
<script setup lang="ts">
import{computed,ref}from'vue';import{onShow}from'@dcloudio/uni-app';import{getOrders,type ClubOrder}from'../../services/orders'
const orders=ref<ClubOrder[]>([]);onShow(()=>orders.value=getOrders());const validCount=computed(()=>orders.value.filter(o=>o.status==='reserved').length)
const go=(url:string)=>uni.redirectTo({url}),goHome=()=>go('/pages/index/index'),goBooking=()=>go('/pages/booking/index'),goOrders=()=>go('/pages/orders/index')
</script>
<style scoped>
.page{min-height:100vh;background:#0d0d12;color:#f5f3ed;padding:32px 20px 90px}.eyebrow{font-size:9px;letter-spacing:2px;color:#d7ff3f}.title{display:block;font-size:30px;font-weight:850;margin-top:6px}.member-card{height:220px;border-radius:14px;margin-top:24px;padding:20px;position:relative;overflow:hidden;color:#0b0b0e;background:linear-gradient(135deg,#e3ff78 0%,#a5cb25 50%,#768f20 100%);box-shadow:0 18px 40px rgba(117,145,32,.12)}.shine{position:absolute;width:230px;height:230px;border:1px solid rgba(255,255,255,.35);border-radius:50%;right:-80px;top:-90px}.card-top,.card-bottom{position:relative;display:flex;justify-content:space-between}.brand{font-weight:900;letter-spacing:3px}.brand span{color:#fff}.chip{font-size:22px}.tier{display:block;font-size:48px;font-weight:900;letter-spacing:-2px;margin-top:38px}.card-bottom{position:absolute;left:20px;right:20px;bottom:19px;align-items:end;font-size:10px}.card-bottom span,.card-bottom b{display:block}.card-bottom span{font-size:7px;letter-spacing:2px;opacity:.55}.card-bottom b{font-size:11px;margin-top:4px}.stats{display:grid;grid-template-columns:repeat(3,1fr);margin:18px 0 30px;background:#17171e;border:1px solid #282830;border-radius:11px;padding:19px 0}.stats view{text-align:center;border-right:1px solid #292930}.stats view:last-child{border:0}.stats b,.stats span{display:block}.stats b{font-size:20px}.stats span{color:#686871;font-size:9px;margin-top:5px}.section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.section-head text{font-size:17px;font-weight:800}.section-head span{font-size:9px;color:#686871}.benefits{background:#17171e;border:1px solid #282830;border-radius:12px;padding:0 16px}.benefits>view{height:73px;display:flex;align-items:center;border-bottom:1px solid #292930}.benefits>view:last-child{border:0}.icon{width:39px;height:39px;border-radius:9px;background:#252a19;color:#d7ff3f;display:flex;align-items:center;justify-content:center;font-size:17px;margin-right:12px}.benefits view view{flex:1}.benefits b,.benefits span{display:block}.benefits b{font-size:12px}.benefits span{font-size:9px;color:#66666f;margin-top:5px}.arrow{font-size:18px;color:#55555e}.locked{opacity:.45}.locked .arrow{font-size:8px}.progress{margin-top:18px;background:#17171e;border:1px solid #282830;border-radius:12px;padding:17px}.progress-head{display:flex;justify-content:space-between;font-size:10px}.track{height:4px;background:#292930;border-radius:4px;margin:14px 0 10px}.track span{display:block;width:4%;height:100%;background:#d7ff3f}.hint{font-size:8px;color:#5e5e67}.nav{position:fixed;z-index:10;bottom:0;left:50%;transform:translateX(-50%);width:min(480px,100%);height:70px;background:rgba(13,13,18,.96);border-top:1px solid #22222a;display:grid;grid-template-columns:repeat(4,1fr)}.nav view{display:flex;flex-direction:column;align-items:center;justify-content:center;color:#62626b;font-size:17px}.nav span{font-size:9px;margin-top:4px}.nav .active{color:#d7ff3f}
</style>
