<template><view class="page">
  <view class="head"><text class="eyebrow">RESERVATIONS</text><text class="title">我的订单</text><text class="count">{{activeCount}} 个有效预订</text></view>
  <view class="tabs"><text class="active">全部</text><text>待到店</text><text>已完成</text><text>已取消</text></view>
  <view v-if="!orders.length" class="empty"><view class="empty-icon">⌁</view><text class="empty-title">今晚还没有安排</text><text class="muted">挑一个喜欢的台位，开始你的夜晚</text><button @click="goBooking">查看台位</button></view>
  <view v-else class="list"><view v-for="order in orders" :key="order.id" :class="['order',order.status]">
    <view class="order-head"><view><text class="order-label">HOLE CLUB</text><text class="id">{{order.id}}</text></view><text class="status">{{order.status==='reserved'?'待到店':'已取消'}}</text></view>
    <view class="date-block"><view class="day"><b>{{day(order.date)}}</b><span>{{month(order.date)}}</span></view><view><text class="date">{{order.date}}</text><text class="time">{{order.session}} 入场</text></view></view>
    <view class="line"></view><view class="info"><view><span>预订台位</span><b>{{order.seats.join('、')}}</b></view><view><span>预订人</span><b>{{order.guestName}} · {{mask(order.phone)}}</b></view></view>
    <button v-if="order.status==='reserved'" class="cancel" @click="cancel(order.id)">取消预订</button>
  </view></view>
  <view class="nav"><view @click="goHome"><text>○</text><span>首页</span></view><view @click="goBooking"><text>⌁</text><span>订台</span></view><view class="active"><text>≡</text><span>订单</span></view><view @click="goMember"><text>◇</text><span>我的</span></view></view>
</view></template>
<script setup lang="ts">
import {computed,ref} from 'vue';import{onShow}from'@dcloudio/uni-app';import{getOrders,cancelOrder,type ClubOrder}from'../../services/orders'
const orders=ref<ClubOrder[]>([]);onShow(()=>orders.value=getOrders());const activeCount=computed(()=>orders.value.filter(o=>o.status==='reserved').length)
const go=(url:string)=>uni.redirectTo({url}),goHome=()=>go('/pages/index/index'),goBooking=()=>go('/pages/booking/index'),goMember=()=>go('/pages/member/index')
const mask=(p:string)=>p.replace(/(\d{3})\d{4}(\d+)/,'$1****$2'),day=(d:string)=>d.slice(-2),month=(d:string)=>['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'][Number(d.slice(5,7))-1]
const cancel=(id:string)=>uni.showModal({title:'取消预订',content:'确认取消这笔预订吗？',success:r=>{if(r.confirm){cancelOrder(id);orders.value=getOrders()}}})
</script>
<style scoped>
.page{min-height:100vh;background:#0d0d12;color:#f5f3ed;padding:32px 20px 90px}.head{position:relative}.eyebrow{font-size:9px;letter-spacing:2px;color:#d7ff3f}.title{display:block;font-size:30px;font-weight:850;margin-top:6px}.count{position:absolute;right:0;bottom:3px;color:#686871;font-size:10px}.tabs{display:flex;gap:25px;margin-top:28px;border-bottom:1px solid #24242b;height:38px}.tabs text{font-size:11px;color:#686871;height:38px}.tabs .active{color:#f4f3ed;border-bottom:2px solid #d7ff3f}.empty{display:flex;flex-direction:column;align-items:center;text-align:center;padding:125px 20px}.empty-icon{font-size:34px;color:#d7ff3f;border:1px solid #303038;width:68px;height:68px;border-radius:50%;display:flex;align-items:center;justify-content:center}.empty-title{font-size:18px;font-weight:800;margin-top:22px}.muted{font-size:11px;color:#65656e;margin-top:9px}.empty button{margin-top:28px;width:150px;height:45px;background:#d7ff3f;color:#09090d;border-radius:5px;font-size:12px;font-weight:800}.list{margin-top:20px}.order{background:#17171e;border:1px solid #292931;border-radius:13px;padding:18px;margin-bottom:14px}.order.cancelled{opacity:.5}.order-head{display:flex;justify-content:space-between}.order-label{display:block;font-size:9px;letter-spacing:2px;color:#d7ff3f}.id{display:block;font-size:9px;color:#5e5e67;margin-top:4px}.status{font-size:10px;color:#d7ff3f;background:#252a19;padding:6px 9px;border-radius:20px;height:25px}.cancelled .status{color:#888;background:#28282e}.date-block{display:flex;align-items:center;margin:22px 0}.day{width:50px;height:55px;background:#d7ff3f;color:#09090d;display:flex;flex-direction:column;align-items:center;justify-content:center;margin-right:14px}.day b{font-size:22px}.day span{font-size:8px}.date,.time{display:block}.date{font-size:15px;font-weight:750}.time{font-size:10px;color:#74747d;margin-top:5px}.line{height:1px;background:#28282f}.info{padding-top:12px}.info view{display:flex;justify-content:space-between;margin-top:7px}.info span{font-size:10px;color:#676770}.info b{font-size:11px}.cancel{height:38px;margin:15px 0 0;background:transparent;border:1px solid #383840;color:#999;border-radius:5px;font-size:10px}.nav{position:fixed;z-index:10;bottom:0;left:50%;transform:translateX(-50%);width:min(480px,100%);height:70px;background:rgba(13,13,18,.96);border-top:1px solid #22222a;display:grid;grid-template-columns:repeat(4,1fr)}.nav view{display:flex;flex-direction:column;align-items:center;justify-content:center;color:#62626b;font-size:17px}.nav span{font-size:9px;margin-top:4px}.nav .active{color:#d7ff3f}
</style>
