<template><view class="page">
  <view class="search"><text>⌕</text><input v-model="query" placeholder="搜索客户、手机号或台位"/></view>
  <view class="tabs"><button v-for="t in tabs" :key="t" :class="{active:tab===t}" @click="tab=t">{{t}}<span v-if="count(t)"> {{count(t)}}</span></button></view>
  <view class="list"><view v-for="order in visible" :key="order.id" class="order" @click="selected=order">
    <view class="top"><view class="table-id">{{order.tableId}}</view><view><b>{{order.customerName}} · {{order.guestCount}}人</b><span>{{order.arrivalTime}} 到店 · 销售 {{order.salesName}}</span></view><text :class="['badge',order.status]">{{statusText[order.status]}}</text></view>
    <view class="bottom"><text>{{order.items.map(i=>i.name).join('、')||'未选择套餐'}}</text><b>¥{{total(order).toLocaleString()}}</b></view>
  </view><view v-if="!visible.length" class="empty">暂无相关订单</view></view>
  <button class="fab" @click="goCreate">＋</button>
  <view v-if="selected" class="mask" @click="selected=null"><view class="sheet" @click.stop><view class="handle"></view><view class="sheet-title"><view><b>{{selected.tableId}} · {{selected.customerName}}</b><span>{{selected.id}}</span></view><text :class="['badge',selected.status]">{{statusText[selected.status]}}</text></view><view class="detail"><view><span>到店时间</span><b>{{selected.date}} {{selected.arrivalTime}}</b></view><view><span>联系电话</span><b>{{mask(selected.phone)}}</b></view><view><span>订单金额</span><b>¥{{total(selected).toLocaleString()}}</b></view><view><span>归属销售</span><b>{{selected.salesName}}</b></view></view><view class="ops"><button v-if="selected.status==='reserved'" @click="move('arrived')">确认到店 / 开台</button><button v-if="['arrived','serving'].includes(selected.status)" @click="addDrink">添加酒水</button><button v-if="['arrived','serving'].includes(selected.status)" class="primary" @click="checkout">收银结账</button><button v-if="selected.status==='cleaning'" class="primary" @click="move('completed')">完成清台</button></view></view></view>
</view></template>
<script setup lang="ts">
import{computed,ref}from'vue';import{onShow}from'@dcloudio/uni-app';import{getOrders,updateStatus,addItem,total,type ClubOrder,type OrderStatus}from'../../services/orders'
const orders=ref<ClubOrder[]>([]),selected=ref<ClubOrder|null>(null),query=ref(''),tabs=['全部','待到店','进行中','已完成'],tab=ref('全部');onShow(()=>orders.value=getOrders())
const statusText:Record<OrderStatus,string>={reserved:'待到店',arrived:'已到店',serving:'消费中',cleaning:'待清台',completed:'已完成',cancelled:'已取消'}
const match=(o:ClubOrder,t:string)=>t==='全部'||(t==='待到店'&&o.status==='reserved')||(t==='进行中'&&['arrived','serving','cleaning'].includes(o.status))||(t==='已完成'&&o.status==='completed'),count=(t:string)=>t==='全部'?orders.value.length:orders.value.filter(o=>match(o,t)).length
const visible=computed(()=>orders.value.filter(o=>match(o,tab.value)&&[o.customerName,o.phone,o.tableId].join('').includes(query.value)))
const refresh=()=>{orders.value=getOrders();if(selected.value)selected.value=orders.value.find(o=>o.id===selected.value?.id)||null},move=(s:OrderStatus)=>{if(!selected.value)return;updateStatus(selected.value.id,s);refresh()}
const addDrink=()=>{if(!selected.value)return;addItem(selected.value.id,{name:'精酿啤酒',qty:6,price:48});updateStatus(selected.value.id,'serving');refresh();uni.showToast({title:'已添加 6 瓶精酿',icon:'success'})}
const checkout=()=>uni.showActionSheet({itemList:['微信','支付宝','现金'],success:r=>{if(!selected.value)return;updateStatus(selected.value.id,'cleaning');refresh();uni.showToast({title:`已记录${['微信','支付宝','现金'][r.tapIndex]}收款`,icon:'success'})}})
const mask=(p:string)=>p.replace(/(\d{3})\d{4}(\d+)/,'$1****$2'),goCreate=()=>uni.navigateTo({url:'/pages/booking/index'})
</script>
<style scoped>
.page{min-height:100vh;background:#f5f5f5;color:#222;padding:14px 14px 70px}.search{height:42px;background:#fff;border-radius:9px;display:flex;align-items:center;padding:0 13px;color:#999}.search input{flex:1;font-size:11px;margin-left:8px}.tabs{display:flex;margin:12px 0;border-bottom:1px solid #ddd}.tabs button{flex:1;margin:0;height:40px;background:transparent;color:#777;font-size:11px;border-radius:0}.tabs button.active{color:#07c160;font-weight:700;border-bottom:2px solid #07c160}.tabs span{font-size:8px}.order{background:#fff;border-radius:11px;margin-bottom:10px;padding:14px}.top{display:flex;align-items:center}.table-id{width:43px;height:43px;border-radius:9px;background:#eaf8ee;color:#07a74f;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:13px;margin-right:11px}.top>view:nth-child(2){flex:1}.top b,.top span{display:block}.top b{font-size:12px}.top span{font-size:9px;color:#999;margin-top:5px}.badge{font-size:9px;border-radius:12px;padding:5px 8px;background:#fff6e6;color:#c98005}.badge.arrived,.badge.serving{background:#edf5ff;color:#3478f6}.badge.cleaning{background:#f0f0f0;color:#777}.badge.completed{background:#eaf8ee;color:#07a74f}.bottom{display:flex;justify-content:space-between;border-top:1px solid #f0f0f0;margin-top:12px;padding-top:11px}.bottom text{font-size:9px;color:#888;max-width:72%;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.bottom b{font-size:12px}.empty{text-align:center;color:#aaa;padding:90px;font-size:11px}.fab{position:fixed;right:max(calc((100vw - 480px)/2 + 18px),18px);bottom:25px;width:52px;height:52px;border-radius:50%;background:#07c160;color:#fff;font-size:26px;box-shadow:0 8px 22px rgba(7,193,96,.3)}.mask{position:fixed;inset:0;background:rgba(0,0,0,.35);display:flex;align-items:end;justify-content:center}.sheet{width:min(480px,100%);background:#fff;border-radius:17px 17px 0 0;padding:10px 18px 24px}.handle{width:32px;height:4px;background:#ddd;border-radius:4px;margin:0 auto 18px}.sheet-title{display:flex;justify-content:space-between;align-items:start}.sheet-title b,.sheet-title span{display:block}.sheet-title b{font-size:19px}.sheet-title span{font-size:9px;color:#999;margin-top:5px}.detail{background:#f7f7f7;border-radius:9px;padding:5px 13px;margin-top:18px}.detail view{height:39px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #e9e9e9}.detail view:last-child{border:0}.detail span{font-size:10px;color:#888}.detail b{font-size:11px}.ops{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:15px}.ops button{margin:0;height:43px;background:#f1f1f1;color:#555;border-radius:7px;font-size:11px}.ops .primary{background:#07c160;color:#fff}
</style>
